#  Copyright 2023-2024 Dataport AöR
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

spring:
  profiles:
    active: default
  application:
    name: aaam-orchestrator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://key-server:8080/realms/POC1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: MARKETPLACE
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8083'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

keycloak:
  client-id: "admin-cli"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/master/protocol/openid-connect"
  admin-base-uri: "${keycloak.base-uri}/admin/realms/POC1"
  authorization-uri: "${keycloak.oidc-base-uri}/auth"
  available-roles-uri: "${keycloak.admin-base-uri}/roles"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout: "${keycloak.oidc-base-uri}/logout"
  jwk-set-uri: "${keycloak.oidc-base-uri}/certs"
  usermgmt-user: "usermgmt"
  usermgmt-pass: "usermgmt"

cors:
  global:
    origins:
    patterns: >
      http://localhost:[*]