spring:
  application:
    name: aaam-orchestrator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://key-server:8080/realms/POC1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: MARKETPLACE
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8083'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"

keycloak:
  client-id: "admin-cli"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/master/protocol/openid-connect"
  admin-base-uri: "${keycloak.base-uri}/admin/realms/POC1"
  authorization-uri: "${keycloak.oidc-base-uri}/auth"
  available-roles-uri: "${keycloak.admin-base-uri}/roles"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout: "${keycloak.oidc-base-uri}/logout"
  jwk-set-uri: "${keycloak.oidc-base-uri}/certs"
  usermgmt-user: "usermgmt"
  usermgmt-pass: "usermgmt"